language: bash

before_install:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - git submodule update --force --init --recursive

script:
    # set the environment variable CURRENT_DIR
    - CURRENT_DIR=`pwd`

    # change to the current directory
    - cd $CURRENT_DIR

    # launch the tests
    #- sh ./runtests.sh

after_success:
